services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod 
    ports:
      - "80:3000" 
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_NAME=${DB_NAME_PROD}
      - WORKERS_API_URL=${WORKERS_API_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}

  db:
    environment:
      MYSQL_DATABASE: ${DB_NAME_PROD}