services:
  backend:
    image: trabunda-backend:latest
    env_file: .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    networks:
      - trabunda_net
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: trabunda_db
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME_DEV}
      #MYSQL_USER: ${DB_USER}
      #MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - trabunda_net

networks:
  trabunda_net:
    driver: bridge

volumes:
  mysql_data: