services:
  backend:
    image: trabunda-backend:latest
    networks:
      - trabunda_net
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: trabunda_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: trabunda
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - trabunda_net

networks:
  trabunda_net:
    driver: bridge

volumes:
  mysql_data: